### ISSUE TITLE
not enough target to hit all agents 

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/eawrapper#4]
I've only 2 agents but with only 1 target it does not test rally many of my agents

Maybe add a loop from 1 to 100 (or to a environment variable)

**Comment by lrochette** [comment]
What about:

all: $(addprefix test,$(shell seq 1 100))

%:
    @echo "Executing $@ on the following host"
    @hostname
    @sleep 5

**Comment by lrochette** [comment]
better yet, display the host and agent name/number. Is there an environment variable to reflect that?

**Comment by kmcknight** [comment]
Good point. A little more exhaustive test would give more confidence that the entire cluster is up and running. I'll have to do some sleuthing to see if there's a way to determine which agent I'm running on (I found ECLOUD_AGENT_NUM, but it doesn't seem to match the node value in the anno file job).
